import type { DocumentLanguage } from '@/db/types';

export const LABEL_KEYS = [
  'invoice',
  'quote',
  'credit',
  'invoiceNumber',
  'quoteNumber',
  'creditNumber',
  'issueDate',
  'dueDate',
  'validUntil',
  'poNumber',
  'from',
  'billTo',
  'quoteTo',
  'shipTo',
  'description',
  'quantity',
  'unitPrice',
  'discount',
  'tax',
  'amount',
  'subtotal',
  'total',
  'paid',
  'balanceDue',
  'amountDue',
  'creditRemaining',
  'depositDue',
  'includes',
  'notes',
  'terms',
  'paymentDetails',
  'payOnline',
  'scanToPay',
  'page',
  'of',
  'paidStamp',
  'voidStamp',
  'overdueStamp',
  'acceptedStamp',
] as const;

export type LabelKey = (typeof LABEL_KEYS)[number];
export type Labels = Record<LabelKey, string>;

export const LANGUAGES: { value: DocumentLanguage; label: string }[] = [
  { value: 'en', label: 'English' },
  { value: 'fr', label: 'Français' },
  { value: 'es', label: 'Español' },
  { value: 'de', label: 'Deutsch' },
  { value: 'pt', label: 'Português' },
  { value: 'it', label: 'Italiano' },
  { value: 'nl', label: 'Nederlands' },
];

const en: Labels = {
  invoice: 'Invoice',
  quote: 'Quote',
  credit: 'Credit Note',
  invoiceNumber: 'Invoice no.',
  quoteNumber: 'Quote no.',
  creditNumber: 'Credit note no.',
  issueDate: 'Issue date',
  dueDate: 'Due date',
  validUntil: 'Valid until',
  poNumber: 'PO number',
  from: 'From',
  billTo: 'Bill to',
  quoteTo: 'Prepared for',
  shipTo: 'Ship to',
  description: 'Description',
  quantity: 'Qty',
  unitPrice: 'Unit price',
  discount: 'Discount',
  tax: 'Tax',
  amount: 'Amount',
  subtotal: 'Subtotal',
  total: 'Total',
  paid: 'Amount paid',
  balanceDue: 'Balance due',
  amountDue: 'Amount due',
  creditRemaining: 'Credit remaining',
  depositDue: 'Deposit due',
  includes: 'Includes',
  notes: 'Notes',
  terms: 'Terms & conditions',
  paymentDetails: 'Payment details',
  payOnline: 'Pay online',
  scanToPay: 'Scan to pay',
  page: 'Page',
  of: 'of',
  paidStamp: 'Paid',
  voidStamp: 'Void',
  overdueStamp: 'Overdue',
  acceptedStamp: 'Accepted',
};

const translations: Record<DocumentLanguage, Labels> = {
  en,
  fr: {
    invoice: 'Facture',
    quote: 'Devis',
    credit: 'Avoir',
    invoiceNumber: 'Facture n°',
    quoteNumber: 'Devis n°',
    creditNumber: 'Avoir n°',
    issueDate: "Date d'émission",
    dueDate: "Date d'échéance",
    validUntil: "Valable jusqu'au",
    poNumber: 'Bon de commande',
    from: 'De',
    billTo: 'Facturé à',
    quoteTo: 'Préparé pour',
    shipTo: 'Livrer à',
    description: 'Description',
    quantity: 'Qté',
    unitPrice: 'Prix unitaire',
    discount: 'Remise',
    tax: 'Taxe',
    amount: 'Montant',
    subtotal: 'Sous-total',
    total: 'Total',
    paid: 'Montant payé',
    balanceDue: 'Solde dû',
    amountDue: 'Montant dû',
    creditRemaining: 'Crédit restant',
    depositDue: 'Acompte dû',
    includes: 'Dont',
    notes: 'Notes',
    terms: 'Conditions générales',
    paymentDetails: 'Informations de paiement',
    payOnline: 'Payer en ligne',
    scanToPay: 'Scanner pour payer',
    page: 'Page',
    of: 'sur',
    paidStamp: 'Payé',
    voidStamp: 'Annulé',
    overdueStamp: 'En retard',
    acceptedStamp: 'Accepté',
  },
  es: {
    invoice: 'Factura',
    quote: 'Presupuesto',
    credit: 'Nota de crédito',
    invoiceNumber: 'Factura n.º',
    quoteNumber: 'Presupuesto n.º',
    creditNumber: 'Nota de crédito n.º',
    issueDate: 'Fecha de emisión',
    dueDate: 'Fecha de vencimiento',
    validUntil: 'Válido hasta',
    poNumber: 'N.º de pedido',
    from: 'De',
    billTo: 'Facturar a',
    quoteTo: 'Preparado para',
    shipTo: 'Enviar a',
    description: 'Descripción',
    quantity: 'Cant.',
    unitPrice: 'Precio unitario',
    discount: 'Descuento',
    tax: 'Impuesto',
    amount: 'Importe',
    subtotal: 'Subtotal',
    total: 'Total',
    paid: 'Importe pagado',
    balanceDue: 'Saldo pendiente',
    amountDue: 'Importe adeudado',
    creditRemaining: 'Crédito restante',
    depositDue: 'Anticipo pendiente',
    includes: 'Incluye',
    notes: 'Notas',
    terms: 'Términos y condiciones',
    paymentDetails: 'Datos de pago',
    payOnline: 'Pagar en línea',
    scanToPay: 'Escanee para pagar',
    page: 'Página',
    of: 'de',
    paidStamp: 'Pagado',
    voidStamp: 'Anulado',
    overdueStamp: 'Vencido',
    acceptedStamp: 'Aceptado',
  },
  de: {
    invoice: 'Rechnung',
    quote: 'Angebot',
    credit: 'Gutschrift',
    invoiceNumber: 'Rechnungsnr.',
    quoteNumber: 'Angebotsnr.',
    creditNumber: 'Gutschriftsnr.',
    issueDate: 'Datum',
    dueDate: 'Fällig am',
    validUntil: 'Gültig bis',
    poNumber: 'Bestellnummer',
    from: 'Von',
    billTo: 'Rechnung an',
    quoteTo: 'Erstellt für',
    shipTo: 'Lieferadresse',
    description: 'Beschreibung',
    quantity: 'Menge',
    unitPrice: 'Einzelpreis',
    discount: 'Rabatt',
    tax: 'Steuer',
    amount: 'Betrag',
    subtotal: 'Zwischensumme',
    total: 'Gesamtbetrag',
    paid: 'Bezahlt',
    balanceDue: 'Offener Betrag',
    amountDue: 'Fälliger Betrag',
    creditRemaining: 'Verbleibendes Guthaben',
    depositDue: 'Fällige Anzahlung',
    includes: 'Enthält',
    notes: 'Anmerkungen',
    terms: 'Geschäftsbedingungen',
    paymentDetails: 'Zahlungsinformationen',
    payOnline: 'Online bezahlen',
    scanToPay: 'Zum Bezahlen scannen',
    page: 'Seite',
    of: 'von',
    paidStamp: 'Bezahlt',
    voidStamp: 'Storniert',
    overdueStamp: 'Überfällig',
    acceptedStamp: 'Angenommen',
  },
  pt: {
    invoice: 'Fatura',
    quote: 'Orçamento',
    credit: 'Nota de crédito',
    invoiceNumber: 'Fatura n.º',
    quoteNumber: 'Orçamento n.º',
    creditNumber: 'Nota de crédito n.º',
    issueDate: 'Data de emissão',
    dueDate: 'Data de vencimento',
    validUntil: 'Válido até',
    poNumber: 'N.º de encomenda',
    from: 'De',
    billTo: 'Faturar a',
    quoteTo: 'Preparado para',
    shipTo: 'Enviar para',
    description: 'Descrição',
    quantity: 'Qtd.',
    unitPrice: 'Preço unitário',
    discount: 'Desconto',
    tax: 'Imposto',
    amount: 'Valor',
    subtotal: 'Subtotal',
    total: 'Total',
    paid: 'Valor pago',
    balanceDue: 'Saldo devedor',
    amountDue: 'Valor devido',
    creditRemaining: 'Crédito restante',
    depositDue: 'Sinal devido',
    includes: 'Inclui',
    notes: 'Notas',
    terms: 'Termos e condições',
    paymentDetails: 'Dados de pagamento',
    payOnline: 'Pagar online',
    scanToPay: 'Digitalize para pagar',
    page: 'Página',
    of: 'de',
    paidStamp: 'Pago',
    voidStamp: 'Anulado',
    overdueStamp: 'Vencido',
    acceptedStamp: 'Aceite',
  },
  it: {
    invoice: 'Fattura',
    quote: 'Preventivo',
    credit: 'Nota di credito',
    invoiceNumber: 'Fattura n.',
    quoteNumber: 'Preventivo n.',
    creditNumber: 'Nota di credito n.',
    issueDate: 'Data di emissione',
    dueDate: 'Scadenza',
    validUntil: 'Valido fino al',
    poNumber: 'N. ordine',
    from: 'Da',
    billTo: 'Fatturare a',
    quoteTo: 'Preparato per',
    shipTo: 'Spedire a',
    description: 'Descrizione',
    quantity: 'Qtà',
    unitPrice: 'Prezzo unitario',
    discount: 'Sconto',
    tax: 'Imposta',
    amount: 'Importo',
    subtotal: 'Subtotale',
    total: 'Totale',
    paid: 'Importo pagato',
    balanceDue: 'Saldo dovuto',
    amountDue: 'Importo dovuto',
    creditRemaining: 'Credito residuo',
    depositDue: 'Acconto dovuto',
    includes: 'Include',
    notes: 'Note',
    terms: 'Termini e condizioni',
    paymentDetails: 'Dati di pagamento',
    payOnline: 'Paga online',
    scanToPay: 'Scansiona per pagare',
    page: 'Pagina',
    of: 'di',
    paidStamp: 'Pagato',
    voidStamp: 'Annullato',
    overdueStamp: 'Scaduto',
    acceptedStamp: 'Accettato',
  },
  nl: {
    invoice: 'Factuur',
    quote: 'Offerte',
    credit: 'Creditnota',
    invoiceNumber: 'Factuurnr.',
    quoteNumber: 'Offertenr.',
    creditNumber: 'Creditnotanr.',
    issueDate: 'Factuurdatum',
    dueDate: 'Vervaldatum',
    validUntil: 'Geldig tot',
    poNumber: 'Ordernummer',
    from: 'Van',
    billTo: 'Factuur aan',
    quoteTo: 'Opgesteld voor',
    shipTo: 'Leveradres',
    description: 'Omschrijving',
    quantity: 'Aantal',
    unitPrice: 'Prijs per eenheid',
    discount: 'Korting',
    tax: 'Belasting',
    amount: 'Bedrag',
    subtotal: 'Subtotaal',
    total: 'Totaal',
    paid: 'Betaald',
    balanceDue: 'Openstaand saldo',
    amountDue: 'Te betalen',
    creditRemaining: 'Resterend tegoed',
    depositDue: 'Aanbetaling verschuldigd',
    includes: 'Inclusief',
    notes: 'Opmerkingen',
    terms: 'Voorwaarden',
    paymentDetails: 'Betalingsgegevens',
    payOnline: 'Online betalen',
    scanToPay: 'Scan om te betalen',
    page: 'Pagina',
    of: 'van',
    paidStamp: 'Betaald',
    voidStamp: 'Geannuleerd',
    overdueStamp: 'Verlopen',
    acceptedStamp: 'Geaccepteerd',
  },
};

export const LABEL_DESCRIPTIONS: Partial<Record<LabelKey, string>> = {
  invoice: 'Invoice title (e.g. "Tax Invoice")',
  quote: 'Quote title (e.g. "Estimate", "Proforma Invoice")',
  credit: 'Credit note title',
};

export function getLabels(
  language: DocumentLanguage = 'en',
  overrides: Record<string, string> = {},
): Labels {
  const base = translations[language] ?? en;
  const result = { ...base };
  for (const key of LABEL_KEYS) {
    const custom = overrides[key];
    if (typeof custom === 'string' && custom.trim() !== '') result[key] = custom.trim();
  }
  return result;
}
