import type { AccountRole, AccountType, ChartTemplateId } from '@/db/types';

export interface ChartAccount {
  code: string;
  name: string;
  type: AccountType;
  role?: AccountRole;
}

type Row = [code: string, name: string, type: AccountType, role?: AccountRole];

const rows = (list: Row[]): ChartAccount[] =>
  list.map(([code, name, type, role]) => ({ code, name, type, ...(role ? { role } : {}) }));

/** Works for most countries: plain names, 4-digit codes. */
const GENERIC = rows([
  ['1000', 'Bank account', 'asset_cash', 'bank'],
  ['1010', 'Cash on hand', 'asset_cash', 'cash'],
  ['1100', 'Accounts receivable', 'asset_receivable', 'receivable'],
  ['1200', 'Inventory', 'asset_current'],
  ['1300', 'Prepaid expenses', 'asset_prepayments'],
  ['1350', 'Sales tax receivable (input tax)', 'asset_current', 'input_tax'],
  ['1400', 'Other current assets', 'asset_current'],
  ['1500', 'Equipment', 'asset_fixed'],
  ['1510', 'Accumulated depreciation – equipment', 'asset_fixed'],
  ['1600', 'Vehicles', 'asset_fixed'],
  ['1610', 'Accumulated depreciation – vehicles', 'asset_fixed'],
  ['1700', 'Other non-current assets', 'asset_non_current'],
  ['2000', 'Accounts payable', 'liability_payable', 'payable'],
  ['2050', 'Company credit card', 'liability_credit_card', 'credit_card'],
  ['2100', 'Sales tax collected (output tax)', 'liability_current', 'output_tax'],
  ['2110', 'Sales tax payable', 'liability_current', 'tax_settlement'],
  ['2200', 'Accrued expenses', 'liability_current'],
  ['2300', 'Payroll liabilities', 'liability_current'],
  ['2400', 'Customer deposits', 'liability_current'],
  ['2500', 'Loans payable', 'liability_non_current'],
  ['3000', "Owner's capital", 'equity', 'capital'],
  ['3100', "Owner's drawings", 'equity', 'drawings'],
  ['3200', 'Retained earnings', 'equity', 'retained_earnings'],
  ['3900', 'Opening balance equity', 'equity', 'opening_balance'],
  ['4000', 'Sales', 'income', 'sales'],
  ['4100', 'Service income', 'income'],
  ['4200', 'Shipping & delivery income', 'income', 'charges'],
  ['4500', 'Other income', 'income_other'],
  ['4510', 'Interest income', 'income_other'],
  ['5000', 'Cost of goods sold', 'expense_direct_cost', 'cost_of_sales'],
  ['5100', 'Subcontractors', 'expense_direct_cost'],
  ['6000', 'General expenses', 'expense', 'expense'],
  ['6010', 'Advertising & marketing', 'expense'],
  ['6020', 'Bank fees & charges', 'expense', 'bank_fees'],
  ['6030', 'Office supplies', 'expense'],
  ['6040', 'Rent', 'expense'],
  ['6050', 'Utilities', 'expense'],
  ['6060', 'Telephone & internet', 'expense'],
  ['6070', 'Software & subscriptions', 'expense'],
  ['6080', 'Travel', 'expense'],
  ['6090', 'Meals & entertainment', 'expense'],
  ['6100', 'Professional fees', 'expense'],
  ['6110', 'Insurance', 'expense'],
  ['6120', 'Postage & shipping', 'expense'],
  ['6130', 'Printing & stationery', 'expense'],
  ['6140', 'Repairs & maintenance', 'expense'],
  ['6150', 'Salaries & wages', 'expense'],
  ['6160', 'Payroll taxes & benefits', 'expense'],
  ['6170', 'Vehicle expenses', 'expense'],
  ['6180', 'Training', 'expense'],
  ['6190', 'Bad debts', 'expense'],
  ['6900', 'Depreciation', 'expense_depreciation'],
  ['7000', 'Exchange gain or loss', 'expense_other', 'fx'],
  ['7100', 'Interest expense', 'expense_other'],
  ['7200', 'Income tax', 'expense_other'],
]);

/** United Kingdom: VAT control accounts and the familiar UK layout. */
const UK = rows([
  ['0010', 'Freehold property', 'asset_fixed'],
  ['0020', 'Plant and machinery', 'asset_fixed'],
  ['0021', 'Plant and machinery – depreciation', 'asset_fixed'],
  ['0030', 'Office equipment', 'asset_fixed'],
  ['0031', 'Office equipment – depreciation', 'asset_fixed'],
  ['0050', 'Motor vehicles', 'asset_fixed'],
  ['0051', 'Motor vehicles – depreciation', 'asset_fixed'],
  ['1001', 'Stock', 'asset_current'],
  ['1100', 'Trade debtors', 'asset_receivable', 'receivable'],
  ['1103', 'Prepayments', 'asset_prepayments'],
  ['1104', 'Other debtors', 'asset_current'],
  ['1200', 'Bank current account', 'asset_cash', 'bank'],
  ['1210', 'Bank deposit account', 'asset_cash'],
  ['1230', 'Petty cash', 'asset_cash', 'cash'],
  ['2100', 'Trade creditors', 'liability_payable', 'payable'],
  ['2105', 'Company credit card', 'liability_credit_card', 'credit_card'],
  ['2109', 'Accruals', 'liability_current'],
  ['2200', 'VAT on sales', 'liability_current', 'output_tax'],
  ['2201', 'VAT on purchases', 'asset_current', 'input_tax'],
  ['2202', 'VAT liability (HMRC)', 'liability_current', 'tax_settlement'],
  ['2210', 'PAYE and NI', 'liability_current'],
  ['2220', 'Net wages', 'liability_current'],
  ['2230', 'Pension contributions', 'liability_current'],
  ['2300', "Directors' loan account", 'liability_current'],
  ['2320', 'Corporation tax', 'liability_current'],
  ['2400', 'Bank loans', 'liability_non_current'],
  ['3000', 'Share capital', 'equity', 'capital'],
  ['3100', 'Dividends and drawings', 'equity', 'drawings'],
  ['3200', 'Retained earnings', 'equity', 'retained_earnings'],
  ['3900', 'Opening balances', 'equity', 'opening_balance'],
  ['4000', 'Sales', 'income', 'sales'],
  ['4010', 'Sales – services', 'income'],
  ['4900', 'Delivery and other charges', 'income', 'charges'],
  ['4910', 'Other income', 'income_other'],
  ['4920', 'Bank interest received', 'income_other'],
  ['5000', 'Cost of sales', 'expense_direct_cost', 'cost_of_sales'],
  ['5100', 'Subcontractors', 'expense_direct_cost'],
  ['5200', 'Postage and carriage', 'expense_direct_cost'],
  ['6000', 'Wages and salaries', 'expense'],
  ['6010', "Employer's NI", 'expense'],
  ['6020', 'Pension costs', 'expense'],
  ['7000', 'Rent and rates', 'expense'],
  ['7100', 'Light, heat and power', 'expense'],
  ['7200', 'Insurance', 'expense'],
  ['7300', 'Repairs and maintenance', 'expense'],
  ['7400', 'Travel and subsistence', 'expense'],
  ['7450', 'Motor expenses', 'expense'],
  ['7500', 'Printing, postage and stationery', 'expense'],
  ['7550', 'Telephone and internet', 'expense'],
  ['7600', 'Software and subscriptions', 'expense'],
  ['7700', 'Advertising and marketing', 'expense'],
  ['7800', 'Accountancy and legal fees', 'expense'],
  ['7900', 'Bank charges', 'expense', 'bank_fees'],
  ['7910', 'Card processing fees', 'expense'],
  ['8000', 'General expenses', 'expense', 'expense'],
  ['8100', 'Bad debts', 'expense'],
  ['8150', 'Entertainment', 'expense'],
  ['8200', 'Depreciation', 'expense_depreciation'],
  ['8300', 'Exchange gains and losses', 'expense_other', 'fx'],
  ['8400', 'Interest paid', 'expense_other'],
  ['8900', 'Corporation tax charge', 'expense_other'],
]);

/** United Arab Emirates: VAT input/output and common UAE accounts. */
const UAE = rows([
  ['1000', 'Bank account', 'asset_cash', 'bank'],
  ['1010', 'Petty cash', 'asset_cash', 'cash'],
  ['1100', 'Accounts receivable', 'asset_receivable', 'receivable'],
  ['1150', 'Post-dated cheques received', 'asset_current'],
  ['1200', 'Inventory', 'asset_current'],
  ['1300', 'Prepaid expenses', 'asset_prepayments'],
  ['1310', 'Security deposits', 'asset_current'],
  ['1350', 'VAT input (recoverable)', 'asset_current', 'input_tax'],
  ['1500', 'Property, plant and equipment', 'asset_fixed'],
  ['1510', 'Accumulated depreciation', 'asset_fixed'],
  ['1600', 'Right-of-use assets', 'asset_non_current'],
  ['2000', 'Accounts payable', 'liability_payable', 'payable'],
  ['2050', 'Company credit card', 'liability_credit_card', 'credit_card'],
  ['2100', 'VAT output', 'liability_current', 'output_tax'],
  ['2110', 'VAT payable (FTA)', 'liability_current', 'tax_settlement'],
  ['2150', 'Post-dated cheques issued', 'liability_current'],
  ['2200', 'Accrued expenses', 'liability_current'],
  ['2300', 'Salaries payable', 'liability_current'],
  ['2310', 'End of service benefits', 'liability_non_current'],
  ['2400', 'Customer advances', 'liability_current'],
  ['2500', 'Long-term loans', 'liability_non_current'],
  ['3000', 'Share capital', 'equity', 'capital'],
  ['3100', "Owner's current account", 'equity', 'drawings'],
  ['3200', 'Retained earnings', 'equity', 'retained_earnings'],
  ['3300', 'Statutory reserve', 'equity'],
  ['3900', 'Opening balance equity', 'equity', 'opening_balance'],
  ['4000', 'Sales', 'income', 'sales'],
  ['4100', 'Service revenue', 'income'],
  ['4200', 'Delivery charges income', 'income', 'charges'],
  ['4500', 'Other income', 'income_other'],
  ['5000', 'Cost of sales', 'expense_direct_cost', 'cost_of_sales'],
  ['6000', 'General and administrative expenses', 'expense', 'expense'],
  ['6010', 'Salaries and allowances', 'expense'],
  ['6020', 'Rent', 'expense'],
  ['6030', 'Utilities', 'expense'],
  ['6040', 'Telephone and internet', 'expense'],
  ['6050', 'Marketing and advertising', 'expense'],
  ['6060', 'Professional fees', 'expense'],
  ['6070', 'Government fees and visas', 'expense'],
  ['6080', 'Travel', 'expense'],
  ['6090', 'Office supplies', 'expense'],
  ['6100', 'Repairs and maintenance', 'expense'],
  ['6110', 'Insurance', 'expense'],
  ['6120', 'Bank charges', 'expense', 'bank_fees'],
  ['6130', 'Software and subscriptions', 'expense'],
  ['6140', 'Postage and courier', 'expense'],
  ['6900', 'Depreciation', 'expense_depreciation'],
  ['7000', 'Exchange gain or loss', 'expense_other', 'fx'],
  ['7100', 'Finance costs', 'expense_other'],
  ['7200', 'Corporate tax', 'expense_other'],
]);

export const CHART_TEMPLATES: Record<ChartTemplateId, { name: string; accounts: ChartAccount[] }> =
  {
    generic: { name: 'Standard', accounts: GENERIC },
    uk: { name: 'United Kingdom', accounts: UK },
    ae: { name: 'United Arab Emirates', accounts: UAE },
  };

export function chartTemplateFor(country: string): ChartTemplateId {
  if (country === 'GB') return 'uk';
  if (country === 'AE') return 'ae';
  return 'generic';
}
